// ═══════════════════════════════════════════════════════════════════════════════
// Firebase Options — Auto-generated by FlutterFire CLI
// ═══════════════════════════════════════════════════════════════════════════════
//
// This file is a placeholder. To link the app to your Firebase project:
//
//   flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
//
// That command will:
//   1. Overwrite this file with real config values for Android & iOS.
//   2. Download google-services.json → android/app/
//   3. Update Android build.gradle files automatically.
//
// Until you run that command, Crashlytics will gracefully fall back to a
// no-op logger so the app never crashes at startup.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for the current platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.\n'
        'Run "flutterfire configure" to generate platform-specific options.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.\n'
          'Run "flutterfire configure" to generate platform-specific options.',
        );
    }
  }

  // ── Android ──────────────────────────────────────────────────────────────
  // These are TEMPLATE values. Run `flutterfire configure` to replace them.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER_AIzaSy_replace_with_flutterfire_configure',
    appId: '1:000000000000:android:xxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  // ── iOS ──────────────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER_AIzaSy_replace_with_flutterfire_configure',
    appId: '1:000000000000:ios:xxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.boon.boon_mobile_scanner',
  );
}
