/**
 * 🌿 Boon Scanner — QR Code Generator
 *
 * Generates QR codes for new biomedical waste items.
 * Uses the Boon backend API to generate and optionally renders locally.
 */

import { generateQR } from './api.js';

/**
 * Generate a QR code for a waste item via the Boon backend.
 * Returns the QR data URL and metadata.
 */
export async function generateWasteQR(data) {
  if (!data.waste_type || !data.category || !data.source_facility) {
    throw new Error('Missing required fields: waste_type, category, source_facility');
  }

  const result = await generateQR({
    waste_type: data.waste_type,
    category: data.category,
    source_facility: data.source_facility,
    department: data.department || 'General',
    weight_kg: data.weight_kg || 1.0,
    container_type: data.container_type || 'bag',
    handler_name: data.handler_name || null,
  });

  return result;
}

/**
 * Render a QR code image onto a canvas or img element.
 */
export function renderQRCode(element, dataUrl, options = {}) {
  const { width = 200, height = 200, label } = options;

  if (element instanceof HTMLImageElement) {
    element.src = dataUrl;
    element.width = width;
    element.height = height;
    element.alt = label || 'QR Code';
  } else if (element instanceof HTMLCanvasElement) {
    const ctx = element.getContext('2d');
    const img = new Image();
    img.onload = () => {
      element.width = width;
      element.height = height;
      ctx.clearRect(0, 0, width, height);
      ctx.drawImage(img, 0, 0, width, height);
    };
    img.src = dataUrl;
  }
}

/**
 * Download QR code as an image file.
 */
export function downloadQRCode(dataUrl, filename = 'boon-qr-code.png') {
  const link = document.createElement('a');
  link.download = filename;
  link.href = dataUrl;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Print a QR code label.
 */
export function printQRCode(dataUrl, label) {
  const printWindow = window.open('', '_blank', 'width=400,height=400');
  if (!printWindow) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Boon QR Label</title>
      <style>
        body {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          min-height: 100vh;
          margin: 0;
          font-family: -apple-system, sans-serif;
          background: white;
        }
        .label {
          text-align: center;
          padding: 20px;
          border: 2px dashed #333;
          border-radius: 8px;
          max-width: 300px;
        }
        img {
          width: 220px;
          height: 220px;
          image-rendering: pixelated;
        }
        h3 {
          margin: 8px 0 4px;
          font-size: 14px;
          color: #333;
        }
        p {
          margin: 2px 0;
          font-size: 11px;
          color: #666;
          font-family: monospace;
        }
        .meta {
          margin-top: 8px;
          font-size: 9px;
          color: #999;
        }
      </style>
    </head>
    <body>
      <div class="label">
        <img src="${dataUrl}" alt="QR Code" />
        <h3>${label || 'Biomedical Waste'}</h3>
        <p>Scan to verify in Boon system</p>
        <div class="meta">Generated by Boon Scanner • ${new Date().toLocaleDateString()}</div>
      </div>
      <script>
        window.onload = () => { window.print(); window.close(); };
      <\/script>
    </body>
    </html>
  `);
  printWindow.document.close();
}
